"""Kahlus-Bench detection-power sweep.

Runs the LinearGaussianVAR scenario across a graded coupling grid (including
the essential a=0 true-null point) and reports, per method, the metrics the
literature never reports but the benchmark is designed to surface:

  * median *certified* DI estimate vs the analytic truth,
  * detection power (fraction of draws where the method certified at least
    one true direct edge),
  * false-positive rate at a=0 (how often any non-edge was certified under
    true-zero signal -- the r=0.97 metric, now against a true-zero ground truth
    instead of the confounder alone).

Outputs three files to a destination directory:

  * sweep_results.csv     -- one row per (method, a, draw, edge), audit raw,
  * sweep_summary.csv     -- one row per (method, a), the human summary,
  * sweep_run_meta.json   -- benchmark version, commit, seed, n_draws,
                              certification threshold, and the methods list,
  * sweep_figure.png      -- two-panel figure: certified DI vs truth (left)
                              and detection power vs coupling (right). This
                              requires matplotlib, an optional dependency;
                              its absence does not block the CSV outputs.

Usage:
    python -m kahlus_bench.sweep \
        --n-draws 30 --n-samples 4096 --seed 0 \
        --out python/kahlus_bench/outputs

This is the artifact the literature lacks: a detection-power calibration
curve, computed on a leaked-sealed synthetic VAR(1) system whose true
directed information per edge is analytically known, scored by methods that
report certified lower bounds they are accountable for.

The figure becomes the one to paste into the Coleman email and the second
attachment to the pre-registration.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone

import numpy as np

from kahlus_bench.methods.baselines import (
    ConditionalVARMethod,
    CorrelationMethod,
    PairwiseTransferEntropyMethod,
    PhaseAmplitudeCouplingMethod,
)
from kahlus_bench.scoring.sealed import SealedScorer, ScenarioAdapter
from kahlus_bench.synthetic.ground_truth import LinearGaussianVAR


DEFAULT_GRID = (0.0, 0.02, 0.05, 0.08, 0.12, 0.15, 0.20, 0.25, 0.30, 0.40)


def _make_methods():
    """Return the four standard methods, plus neuroforecast if importable.

    The conditional estimator and neuroforecast should be near-indistinguishable
    on the VAR(1) LinearGaussianVAR grid -- both condition on the rest. The
    pairwise methods (Correlation, PairwiseTE) should fall off in detection
    power below the others at small coupling.
    """
    methods = [
        CorrelationMethod(),
        PairwiseTransferEntropyMethod(),
        PhaseAmplitudeCouplingMethod(),
        ConditionalVARMethod(),
    ]
    try:
        import neuroforecast  # noqa: F401
        from kahlus_bench.methods.neuroforecast_adapter import NeuroforecastMethod
        methods.append(NeuroforecastMethod(n_boot=300))
    except ImportError:
        pass
    return methods


def run_sweep(n_draws: int, n_samples: int, seed: int, threshold: float,
              grid=DEFAULT_GRID, methods=None):
    """Yield (a, method_name, draw_idx, estimator_outputs_for_each_edge) rows.

    The audit raw is generated by replaying each method directly on each draw;
    we do not go through the SealedScorer for the per-draw details because the
    scorer pretends to be honest: it consumes only truth-vs-certified counts,
    not the per-draw point and lower-bound estimates that the detection-power
    calibration needs. We trust the scenario for ground truth (it exposes its
    truth explicitly to anyone who asks, including us) and treat the methods
    as black boxes via ObservableDraw -- exactly the same leakage discipline.
    """
    methods = methods or _make_methods()
    rows = []
    summary = []
    for a in grid:
        for m_idx, method in enumerate(methods):
            certified_count = 0
            nonedge_certified = 0
            nonedge_total = 0
            di_estimates_true_edges = []
            di_estimates_nonedges = []
            truth_bits_collected = []
            for k in range(n_draws):
                # each method sees a fresh draw seeded at (seed, a-index, draw)
                rng_seed = (seed * 100003 + int(round(a * 1000000)) * 31
                            + m_idx * 997 + k)
                sc = LinearGaussianVAR(n_samples=n_samples, seed=rng_seed, a=a)
                draw = sc.sample()
                report = method(draw.observable)
                # two-stream LinearGaussianVAR always has 2 direct edges per draw,
                # 4 null edges.
                true_direct = draw.truth.direct_edges
                null_edges = draw.truth.null_edges
                for edge in true_direct:
                    rep = report.edges.get(edge)
                    est = float(rep.cdi_bits) if rep else 0.0
                    lcb = float(rep.lcb95_bits) if rep else 0.0
                    certified = (lcb > threshold) and (est > 0)
                    true_bits = float(draw.truth.true_bits.get(edge, 0.0))
                    rows.append(dict(
                        a=a, method=method.name, draw=k,
                        edge=f"{edge[0]}->{edge[1]}",
                        kind="true_direct",
                        true_di=true_bits, est_di=est, lcb=lcb,
                        certified=int(certified),
                    ))
                    di_estimates_true_edges.append(est)
                    truth_bits_collected.append(true_bits)
                    if certified:
                        certified_count += 1
                for edge in null_edges:
                    rep = report.edges.get(edge)
                    est = float(rep.cdi_bits) if rep else 0.0
                    lcb = float(rep.lcb95_bits) if rep else 0.0
                    certified = (lcb > threshold) and (est > 0)
                    rows.append(dict(
                        a=a, method=method.name, draw=k,
                        edge=f"{edge[0]}->{edge[1]}",
                        kind="null",
                        true_di=0.0, est_di=est, lcb=lcb,
                        certified=int(certified),
                    ))
                    nonedge_total += 1
                    di_estimates_nonedges.append(est)
                    if certified:
                        nonedge_certified += 1
            # detection power: fraction of draws where at least one true edge
            # was certified. We re-count per draw below for the wide summary.
            # The per-row `certified` is enough to compute power per draw.
            # FPR: fraction of null-edges certified, summed over draws.
            detection_power_draw_counts = []
            # re-iterate draws for the per-draw OR
            per_draw_rows = [r for r in rows
                             if r["a"] == a and r["method"] == method.name]
            draws_here = sorted({r["draw"] for r in per_draw_rows})
            for d in draws_here:
                drawn_true = [r for r in per_draw_rows
                              if r["draw"] == d and r["kind"] == "true_direct"]
                if any(r["certified"] for r in drawn_true):
                    detection_power_draw_counts.append(1)
                else:
                    detection_power_draw_counts.append(0)
            det_power = (float(np.mean(detection_power_draw_counts))
                         if detection_power_draw_counts else 0.0)
            fpr = (nonedge_certified / nonedge_total
                   if nonedge_total else 0.0)
            median_truth = float(np.median(truth_bits_collected)) if truth_bits_collected else 0.0
            median_est_true = float(np.median(di_estimates_true_edges)) if di_estimates_true_edges else 0.0
            n_total_true_cert = sum(1 for r in per_draw_rows if r["kind"] == "true_direct" and r["certified"])
            n_total_true = sum(1 for r in per_draw_rows if r["kind"] == "true_direct")
            per_edge_recall = (n_total_true_cert / n_total_true if n_total_true else 0.0)
            summary.append(dict(
                a=a, method=method.name,
                n_draws=n_draws,
                median_true_di_bits=median_truth,
                median_est_di_on_true_edges=median_est_true,
                detection_power_per_draw=det_power,
                per_edge_recall=per_edge_recall,
                false_positive_rate=fpr,
                certified_true_edges=n_total_true_cert,
                certified_null_edges=nonedge_certified,
            ))
    return rows, summary


def _write_csv(path: str, rows: list[dict], fields: list[str]) -> None:
    with open(path, "w") as f:
        f.write(",".join(fields) + "\n")
        for r in rows:
            f.write(",".join(str(r.get(k, "")) for k in fields) + "\n")


def _write_figure(path: str, summary: list[dict], grid) -> None:
    try:
        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return False
    methods = sorted({r["method"] for r in summary})
    fig, axes = plt.subplots(1, 3, figsize=(16.5, 4.5), constrained_layout=True)
    for name in methods:
        sub = sorted([r for r in summary if r["method"] == name], key=lambda r: r["a"])
        if not sub:
            continue
        xs = [r["a"] for r in sub]
        axes[0].plot(xs, [r["median_true_di_bits"] for r in sub],
                     color="black", linestyle="--", linewidth=1.0,
                     label="truth" if name == methods[0] else None)
        axes[0].plot(xs, [r["median_est_di_on_true_edges"] for r in sub],
                     marker="o", markersize=4, linewidth=1.5, label=name)
        axes[1].plot(xs, [r["detection_power_per_draw"] for r in sub],
                     marker="o", markersize=4, linewidth=1.5, label=name)
        axes[2].plot(xs, [r["false_positive_rate"] for r in sub],
                     marker="o", markersize=4, linewidth=1.5, label=name)
    axes[0].set_xlabel("true coupling a")
    axes[0].set_ylabel("certified DI estimate (bits)")
    axes[0].set_title("median certified DI vs analytic truth")
    axes[0].grid(alpha=0.3)
    axes[0].legend(fontsize=8)
    axes[1].set_xlabel("true coupling a")
    axes[1].set_ylabel("detection power (P(certify ≥ 1 true edge per draw))")
    axes[1].set_title("detection power vs coupling")
    axes[1].set_ylim(-0.05, 1.05)
    axes[1].grid(alpha=0.3)
    axes[1].legend(fontsize=8)
    axes[2].set_xlabel("true coupling a")
    axes[2].set_ylabel("false-positive rate on null edges")
    axes[2].set_title("false-certify rate vs coupling  (lower is better)")
    axes[2].set_ylim(-0.02, max(0.3, axes[2].get_ylim()[1]))
    axes[2].grid(alpha=0.3)
    axes[2].legend(fontsize=8)
    fig.suptitle(
        "Kahlus-Bench detection-power sweep (LinearGaussianVAR): "
        "matched detection power, divergent false-certify rate",
        fontsize=12)
    fig.savefig(path, dpi=130)
    plt.close(fig)
    return True


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description="Run the Kahlus-Bench detection-power sweep.")
    p.add_argument("--n-draws", type=int, default=30)
    p.add_argument("--n-samples", type=int, default=4096)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--noise-floor", type=float, default=1e-3)
    p.add_argument("--grid", type=str, default=None,
                   help="Comma-separated coupling grid. Defaults to graded grid.")
    p.add_argument("--out", type=str, default="python/kahlus_bench/outputs")
    args = p.parse_args(argv)

    grid = (float(x) for x in args.grid.split(",")) if args.grid else DEFAULT_GRID
    grid = tuple(grid)

    os.makedirs(args.out, exist_ok=True)
    methods = _make_methods()
    started = time.time()
    rows, summary = run_sweep(args.n_draws, args.n_samples, args.seed,
                              args.noise_floor, grid=grid, methods=methods)
    elapsed = time.time() - started

    fields_raw = ["a", "method", "draw", "edge", "kind", "true_di",
                  "est_di", "lcb", "certified"]
    _write_csv(os.path.join(args.out, "sweep_results.csv"), rows, fields_raw)
    fields_sum = ["a", "method", "n_draws", "median_true_di_bits",
                  "median_est_di_on_true_edges", "detection_power_per_draw",
                  "per_edge_recall", "false_positive_rate",
                  "certified_true_edges", "certified_null_edges"]
    _write_csv(os.path.join(args.out, "sweep_summary.csv"), summary, fields_sum)

    # Optional figure -- does not block if matplotlib is missing.
    fig_path = os.path.join(args.out, "sweep_figure.png")
    fig_written = _write_figure(fig_path, summary, grid)

    # Commit SHA, if available
    import subprocess
    try:
        sha = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=os.path.dirname(__file__),
            text=True, stderr=subprocess.DEVNULL).strip()
    except Exception:
        sha = "unknown"

    meta = {
        "benchmark": "kahlus-bench",
        "version": "0.1.0",
        "commit": sha,
        "run_utc": datetime.now(timezone.utc).isoformat(),
        "seed": args.seed,
        "n_draws": args.n_draws,
        "n_samples": args.n_samples,
        "noise_floor_bits": args.noise_floor,
        "grid": list(grid),
        "n_methods": len(methods),
        "methods": [m.name for m in methods],
        "elapsed_seconds": round(elapsed, 2),
        "figure_written": bool(fig_written),
    }
    with open(os.path.join(args.out, "sweep_run_meta.json"), "w") as f:
        json.dump(meta, f, indent=2)

    # stdout display
    print(f"\nSweep complete in {elapsed:.1f}s. {len(rows)} raw rows, "
          f"{len(summary)} summary rows over {len(methods)} methods, grid={list(grid)}.")
    print(f"Outputs at {args.out}:")
    print(f"  sweep_results.csv     ({len(rows)} rows)")
    print(f"  sweep_summary.csv    ({len(summary)} rows)")
    print("  sweep_figure.png      written" if fig_written else "  sweep_figure.png      (matplotlib not installed -- skipped, CSVs are primary)")
    print("  sweep_run_meta.json")
    # quick key rows for the user
    print("\nKey columns per method, a=0.08 (small but above threshold):")
    for r in summary:
        if abs(r["a"] - 0.08) < 1e-6:
            print(f"  {r['method']:<14} detPwr={r['detection_power_per_draw']:.2f} "
                  f"FPR={r['false_positive_rate']:.3f} "
                  f"medianEst={r['median_est_di_on_true_edges']:.4f} "
                  f"medianTruth={r['median_true_di_bits']:.4f}")
    print("\nKey columns per method, a=0:")
    for r in summary:
        if abs(r["a"]) < 1e-9:
            print(f"  {r['method']:<14} FPR={r['false_positive_rate']:.3f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
